config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :companies
  root 'sessions#login'
  get 'login' => 'sessions#login'
  get 'home' => 'sessions#home'
  get 'logout' => 'sessions#logout'
  post 'sessions/login_process' => 'sessions#login_process'
  get 'sessions/login_process' => 'sessions#login_process'

end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :name, presence: true

  dragonfly_accessor :logo
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  belongs_to :company

  def get_full_name
    self.first_name.to_s + " " + self.last_name.to_s
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, format: { with: proc {format_email} }
  validates :encrypted_password, presence: true

  def self.format_email
    /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user_from_email_and_token
    authn_token = session[:authn_token]

    user = User.find_by(email: session[:email])
    redirect_to "/login.html?notice=Login First" if user.nil? || user.authn_token != session[:authn_token]
  end

  def authorize_user_menu
    redirect_to "/home.html?notice=You are not authorized" if session[:email] == "user@grtech.com.my"
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user_from_email_and_token
  before_action :authorize_user_menu

  # GET /companies
  # GET /companies.json
  def index
    page = params[:start] || 0
    per_page = params[:length] || 10
    @companies = Company.paginate(page: (page.to_i == 0? 1 : (page.to_i/per_page.to_i) + 1), per_page: per_page.to_i)
    respond_to do |format|
      format.html
      format.json{
        render :json => {draw: params[:draw], recordsTotal: Company.all.count, recordsFiltered: Company.all.count, data: @companies}
      }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:id, :name, :email, :logo, :website)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user_from_email_and_token
  before_action :authorize_user_menu

  # GET /employees
  # GET /employees.json
  def index
    page = params[:start] || 0
    per_page = params[:length] || 10
    @employees = Employee.paginate(page: (page.to_i == 0? 1 : (page.to_i/per_page.to_i) + 1), per_page: per_page.to_i)
    @employees = @employees.map{ |m| m.attributes.merge({full_name: m.get_full_name, company: {id: m.company_id, name: m.try(:company).try(:name)}})}
    respond_to do |format|
      format.html
      format.json{
        render :json => {draw: params[:draw], recordsTotal: Employee.all.count, recordsFiltered: Employee.all.count, data: @employees}
      }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:id, :first_name, :last_name, :company_id, :email, :phone)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_user_from_email_and_token, only: [:home]
  def login_process
    user = User.find_by(email: params[:user][:email])
    redirect_to "/login.html?notice=Invalid login or password" unless user.present?

    password_valid = (BCrypt::Password.new(user.encrypted_password) == params[:user][:password])

    redirect_to "/login.html?notice=Invalid login or password" unless password_valid

    @email = user.email
    @authn_token = SecureRandom.hex
    user.update_column(:authn_token, @authn_token)

    session[:email] = @email
    session[:authn_token] = @authn_token

    redirect_to "/home.html"
  end

  def login
    @user = User.new
  end

  def logout
    session[:email] = nil
    session[:authn_token] = nil

    redirect_to "/login.html?notice=Logout sucessfully"
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company, :html => {:multipart => true}) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :logo_name %><br>
    <%= f.file_field :logo %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Companies</h1>

<table id="example" class="display" style="width:100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Logo</th>
      <th>Website</th>
      <th>Action</th>
    </tr>
  </thead>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

<script type="text/javascript">
  $(document).ready(function() {
    $('#example').DataTable( {
        "processing": true,
        "serverSide": true,
        "ajax": "../companies.json",
        "columns" : [
          {data: 'name'},
          {data: 'email'},
          {
            data: 'logo_uid',
            render: function(data, type) {
              return '<img src="/assets/'+ data +'" width=150" height="70">';
            }
          },
          {data: 'website'},
          {
            data: 'id',
            render: function(data, type) {
              return '<a href="/companies/'+ data +'/edit">Edit</a>&nbsp;<a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/companies/'+ data +'">Destroy</a>';
            }
          }
        ]
    } );
} );
</script>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @company.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @company.email %>
</p>

<p>
  <strong>Logo uid:</strong>
  <%= @company.logo_uid %>
</p>

<p>
  <strong>Logo name:</strong>
  <%= @company.logo_name %>
</p>

<p>
  <strong>Website:</strong>
  <%= @company.website %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.number_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees</h1>

<table id="example" class="display" style="width:100%">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Company</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Action</th>
    </tr>
  </thead>
</table>
<br>

<%= link_to 'New Employee', new_employee_path %>

<script type="text/javascript">
  $(document).ready(function() {
    $('#example').DataTable( {
        "processing": true,
        "serverSide": true,
        "ajax": "../employees.json",
        "columns" : [
          {data: 'first_name'},
          {data: 'last_name'},
          {
            data: 'company',
            render: function(data, type) {
              return '<a href="/companies/'+ data.id +'/edit" target="_blank">'+ data.name +'</a>';
            }
          },
          {data: 'email'},
          {data: 'phone'},
          {
            data: 'id',
            render: function(data, type) {
              return '<a href="/employees/'+ data +'/edit">Edit</a>&nbsp;<a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/employees/'+ data +'">Destroy</a>';
            }
          }
        ]
    } );
} );
</script>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @employee.id %>
</p>

<p>
  <strong>First name:</strong>
  <%= @employee.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @employee.company_id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee.phone %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GrTech</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.11.3/datatables.min.css"/>
 
  <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.3/datatables.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<%
if session[:email].present? && session[:authn_token].present?
%>
<h3>Welcome <%= session[:email] %>, <a href="/logout">Logout</a></h3>
<h3><a href="/home">Home</a>
<%
if session[:email] != "user@grtech.com.my"
%>
&nbsp;&nbsp;&nbsp;&nbsp;<a href="/companies">Company</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/employees">Employee</a></h3>
<%
end
%>
<%
end
%>
<%= yield %>

</body>
</html>